# Generated by Django 4.2 on 2025-05-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Contributions", "0002_contributionstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributionstatus",
            name="status",
            field=models.CharField(
                choices=[("Đã nộp", "ĐÃ NỘP"), ("Chưa nộp", "CHƯA NỘP")],
                default="CHƯA NỘP",
                max_length=10,
            ),
        ),
    ]
