# Generated by Django 4.2 on 2025-05-30 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("HouseHold_Resident", "0001_initial"),
        ("Collections", "0001_initial"),
        ("Contributions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PAID", "Paid"), ("UNPAID", "Unpaid")],
                        default="UNPAID",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_by_code",
                        to="Collections.collection",
                        to_field="code",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_statuses",
                        to="HouseHold_Resident.household",
                    ),
                ),
            ],
            options={
                "unique_together": {("household", "code")},
            },
        ),
    ]
