# Generated by Django 5.2 on 2025-05-27 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Collections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="description",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="collection",
            name="feeDate",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="collection",
            name="feeEndDate",
            field=models.DateField(blank=True, null=True),
        ),
    ]
