# Generated by Django 4.2 on 2025-06-04 15:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("HouseHold_Resident", "0001_initial"),
        ("Collections", "0002_collection_description_collection_feedate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContributionStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Đã nộp", "ĐÃ NỘP"), ("Chưa nộp", "CHƯA NỘP")],
                        default="CHƯA NỘP",
                        max_length=10,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_by_code",
                        to="Collections.collection",
                        to_field="code",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contribution_statuses",
                        to="HouseHold_Resident.household",
                    ),
                ),
            ],
            options={
                "unique_together": {("household", "code")},
            },
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("payment_date", models.DateField()),
                ("is_reconciled", models.BooleanField(default=False)),
                (
                    "code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions_by_code",
                        to="Collections.collection",
                        to_field="code",
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="HouseHold_Resident.household",
                    ),
                ),
            ],
            options={
                "unique_together": {("household", "code")},
            },
        ),
    ]
