# Generated by Django 5.2 on 2025-06-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Contributions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributionstatus",
            name="status",
            field=models.CharField(
                choices=[("ĐÃ NỘP", "ĐÃ NỘP"), ("CHƯA NỘP", "CHƯA NỘP")],
                default="CHƯA NỘP",
                max_length=10,
            ),
        ),
    ]
