# Generated by Django 4.2 on 2025-06-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HouseHold_Resident", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizen",
            name="id_card_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
