# Generated by Django 5.2 on 2025-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HouseHold_Resident", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="citizen",
            name="job",
        ),
        migrations.RemoveField(
            model_name="citizen",
            name="previous_residence",
        ),
        migrations.RemoveField(
            model_name="citizen",
            name="workplace",
        ),
        migrations.AddField(
            model_name="citizen",
            name="status",
            field=models.CharField(
                choices=[
                    ("sinh_song", "Sinh sống"),
                    ("tam_vang", "Tạm vắng"),
                    ("tam_tru", "Tạm trú"),
                ],
                default="sinh_song",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="number_people",
            field=models.IntegerField(default=0),
        ),
    ]
